### ISSUE TITLE
logseq furigana mode is not working

### ISSUE THREAD

**Issue by Broiler7081** [daviddavo/logseq-furigana#2]
# Behaviour
![image](https://github.com/daviddavo/logseq-furigana/assets/75277768/49b653a7-2df1-427c-9eaf-e1d723f10167)

- From the plugin I also got this gear in the upper right corner. It seems to have no function.
- _/Anki Furigana to Ruby_ and _/Obsidian Furigana to Ruby_  working as expected

# Plugins
![image](https://github.com/daviddavo/logseq-furigana/assets/75277768/666fc0e3-4628-4f7f-acba-1534a912450e)

# System
+ Pop!_OS 22.04 LTS
+ Flatpak Version: Logseq 0.9.8

**Comment by daviddavo** [comment]
Sorry, I used a template and I forgot to delete it
